org: kevinlemamartinez
app: gsd-api
service: GSD
configValidationMode: error

package:
  individually: true

# Load .env as environment variables
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ${env:AWS_REGION}
  lambdaHashingVersion: 20201221

  httpApi:
    authorizers:
      customCognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: ${env:COGNITO_ISSUER_URL}
        audience:
          - ${env:COGNITO_CLIENT_ID}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_NUMBER}:table/Cards*"

  logs:
    httpApi: true

functions:
  postCard:
    handler: lambda/postCard/postCard-handler.postCard
    events:
      - httpApi:
          method: POST
          path: /cards
          authorizer: customCognitoAuthorizer
      - httpApi:
          method: PUT
          path: /cards
          authorizer: customCognitoAuthorizer
    package:
      patterns:
        - '!./**'
        - ./lambda/postCard/** 
    memorySize: 128

  getCards:
    handler: lambda/getCards-handler.getCards
    events:
      - httpApi:
          method: GET
          path: /cards
          authorizer: customCognitoAuthorizer
    package:
      patterns:
        - '!./**'
        - ./lambda/getCards-handler.js 
    memorySize: 128

  getCard:
    handler: lambda/getCard-handler.getCard
    events:
      - httpApi:
          method: GET
          path: /cards/{cardId}
          authorizer: customCognitoAuthorizer
    package:
      patterns:
        - '!./**'
        - ./lambda/getCard-handler.js  
    memorySize: 128

  deleteCard:
    handler: lambda/deleteCard-handler.deleteCard
    events:
      - httpApi: 
          method: DELETE
          path: /cards/{cardId}
          authorizer: customCognitoAuthorizer
    package:
      patterns:
        - '!./**'
        - ./lambda/deleteCard-handler.js       
    memorySize: 128

resources:
  Resources:

    # Bucket to host the static website
    GSDWebBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: gsd-web
        WebsiteConfiguration:
            IndexDocument: index.html
    GSDWebBucketPolicy: 
      Type: AWS::S3::BucketPolicy
      Properties: 
        Bucket:
          Ref: "GSDWebBucket"
        PolicyDocument:
          Statement:
            -
              Effect: "Allow"
              Principal: "*"
              Action:
                - "s3:GetObject"
              Resource:
                Fn::Join:
                  - ""
                  - 
                    - "arn:aws:s3:::"
                    - 
                      Ref: "GSDWebBucket"
                    - "/*"

    # Database
    CardsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: Cards
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
          -  
            AttributeName: cardId
            AttributeType: S
          -  
            AttributeName: fixed_creationTimestamp_tag
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
          -
            AttributeName: cardId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        LocalSecondaryIndexes:
          -
            IndexName : tagIndex
            KeySchema :
              -
                AttributeName : userId
                KeyType : HASH
              -
                AttributeName : fixed_creationTimestamp_tag
                KeyType : RANGE                         
            Projection :
              ProjectionType : ALL